### ISSUE TITLE
CBTNuggets Says : Conflict Error retrying in few seconds..

### ISSUE THREAD

**Issue by Daiablo** [r0oth3x49/cbtnuggets-dl#1]
After a couple of downloads this error starts to appear. If I close the window and restart the process it resumes nicely for a few videos then the error occurs again.

I'm guessing this may be a timeout on the CBT Nuggets site in an attempt to block mass downloading. Would it be possible to implement a wait step when this message is returned - perhaps 5 minutes before retrying to see if this allows it to continue successfully? Or perhaps implement a new wait parameter so users can adjust this themselves?

Happy to be a guinea pig for you. Keep up the good work.

**Comment by r0oth3x49** [comment]
@Daiablo thanks, i 'll soon update the code.
