### ISSUE TITLE
Failed to extract course json information

### ISSUE THREAD

**Issue by DerrickLamers** [r0oth3x49/cbtnuggets-dl#6]
I receive the following error:

Failed to extract course json information

**Comment by r0oth3x49** [comment]
@DerrickLamers thanks for the report i will try to reproduce & fix ASAP.

**Comment by digeshacharya** [comment]
having same problem ...:(

**Comment by brudaine1200** [comment]
[*] : Username : *********
[*] : Password : *********
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'border gateway protocol basic'.
[*] : Trying to login as (*********)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[-] : Failed to extract course json information..

Can't wait for this to get resolved.  Will keep checking back.

**Comment by r0oth3x49** [comment]
@brudaine1200 @DerrickLamers i don't have any account on cbtnuggets so i might need an account to test & fix.

**Comment by Propermike** [comment]
i am not a programmer but would like to know how to use this programe to download CBT nuggets any Tutorial

**Comment by IEEE-802dot1x** [comment]
Any updates on this issue?
